<a href="https://colab.research.google.com/github/ExpectationsHACK/GOMYCODE/blob/main/let's_build_create_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
1
import numpy as np

# create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# convert the NumPy array to a list
lst = arr.tolist()

# print the original NumPy array
print("NumPy array:", arr)

# print the converted list
print("List:", lst)


NumPy array: [1 2 3 4 5]
List: [1, 2, 3, 4, 5]


In [3]:
2
#Manually (without direct function)
import numpy as np

# create a 3x3 array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# compute the sum of the diagonal elements manually
diagonal_sum = 0
for i in range(arr.shape[0]):
    diagonal_sum += arr[i][i]

# print the sum of the diagonal elements
print("Sum of diagonal elements:", diagonal_sum)


 #Using the trace function

# create a 3x3 array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# compute the sum of the diagonal elements using the trace function
diagonal_sum = np.trace(arr)

# print the sum of the diagonal elements
print("Sum of diagonal elements:", diagonal_sum)



Sum of diagonal elements: 15
Sum of diagonal elements: 15


In [5]:
3
import numpy as np

# create a 2x2 array
a = np.array([[1, 2], [3, 5]])

# set the value of x
x = 2

# get all the values in the array that are higher than x
result = a[a > x]

# print the result
print("Values higher than", x, "in array a:", result)



Values higher than 2 in array a: [3 5]


In [6]:
4
import numpy as np

# create two 2x3 arrays
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

# apply addition by hand to create a new array C
C = np.zeros_like(A)  # create a new array of the same shape as A
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        C[i][j] = A[i][j] + B[i][j]

# print the original arrays and the new array C
print("Array A:", A)
print("Array B:", B)
print("Array C:", C)


Array A: [[1 2 3]
 [4 5 6]]
Array B: [[ 7  8  9]
 [10 11 12]]
Array C: [[ 8 10 12]
 [14 16 18]]


In [7]:
5
import numpy as np

# create a 3x3 matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# compute the mean of each row
row_means = np.mean(matrix, axis=1)

# subtract the row means from the matrix
centered_matrix = matrix - row_means.reshape(-1, 1)

# print the original matrix and the centered matrix
print("Original matrix:\n", matrix)
print("Centered matrix:\n", centered_matrix)


Original matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Centered matrix:
 [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
